#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Deblan\Console\Application;
use Deblan\Console\Command\Input\Input;

$app = new Application();

$app->chdir(__DIR__.'/../');

$app->addCommandsPath('src/Deblan/PowerDNS/Command/', 'Deblan\\PowerDNS\\Command');
$app->initPropel();
$app->loadCommands();
$app->run(new Input());
